# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180925_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
    ]
